version: '3.1'

services:

  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3316:3306
