# 测试环境
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3316/example?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: example
    separator: //

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
debug: false